services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "8970:3000"
    volumes:
      - ./server/data:/data:ro
      - ./metabase/config/${APP_ENV:-develop}:/metabase-data
    environment:
      - APP_ENV=${APP_ENV:-develop}
      - MB_DB_FILE=/metabase-data/metabase.db
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
